import requests
import uuid

BASE_URL = "http://localhost:5173"

HEADERS = {
    "Content-Type": "application/json"
}

def test_verify_bug_report_submission_and_metadata_storage():
    # 1. Create a new bug report with detailed metadata
    bug_report_payload = {
        "title": f"Test Bug Report {uuid.uuid4()}",
        "description": "This bug report is generated by an automated test case to verify metadata storage.",
        "version": "1.2.3",
        "severity": "Critical",
        "status": "Open",
        "stepsToReproduce": [
            "Step 1: Open application",
            "Step 2: Navigate to bug reporting section",
            "Step 3: Submit bug report with metadata"
        ],
        "expectedResult": "Bug report should be stored and retrievable with all metadata fields intact",
        "actualResult": "Bug report submission successful"
    }

    bug_id = None
    try:
        create_response = requests.post(
            f"{BASE_URL}/api/data/bugs",
            headers=HEADERS,
            json=bug_report_payload,
            timeout=30
        )
        assert create_response.status_code in (200, 201), f"Unexpected status code on bug report creation: {create_response.status_code}"
        try:
            create_data = create_response.json()
        except Exception as e:
            assert False, f"Creation response is not valid JSON: {e}, Response text: {create_response.text}"
        assert "id" in create_data, "Bug report creation response missing 'id' field"
        bug_id = create_data["id"]

        for key in ["title", "description", "version", "severity", "status"]:
            assert create_data.get(key) == bug_report_payload[key], f"{key} mismatch after creation"

        get_response = requests.get(
            f"{BASE_URL}/api/data/bugs/{bug_id}",
            headers=HEADERS,
            timeout=30
        )
        assert get_response.status_code == 200, f"Unexpected status code when retrieving bug report: {get_response.status_code}"
        try:
            get_data = get_response.json()
        except Exception as e:
            assert False, f"Get response is not valid JSON: {e}, Response text: {get_response.text}"

        for key in ["title", "description", "version", "severity", "status", "stepsToReproduce", "expectedResult", "actualResult"]:
            assert get_data.get(key) == bug_report_payload[key], f"{key} mismatch after retrieval"

        invalid_payload = {
            "description": "Missing title field",
            "version": "1.0.0",
            "severity": "Low",
            "status": "Open"
        }
        invalid_response = requests.post(
            f"{BASE_URL}/api/data/bugs",
            headers=HEADERS,
            json=invalid_payload,
            timeout=30
        )
        assert invalid_response.status_code in (400, 422), "Invalid bug report submission should fail with 400 or 422"

        invalid_severity_payload = bug_report_payload.copy()
        invalid_severity_payload["severity"] = "InvalidSeverityLevel"
        invalid_severity_response = requests.post(
            f"{BASE_URL}/api/data/bugs",
            headers=HEADERS,
            json=invalid_severity_payload,
            timeout=30
        )
        assert invalid_severity_response.status_code in (400, 422), "Bug report with invalid severity should fail validation"

        list_response = requests.get(
            f"{BASE_URL}/api/data/bugs",
            headers=HEADERS,
            timeout=30
        )
        assert list_response.status_code == 200, "Failed to fetch bugs list"
        try:
            bugs_list = list_response.json()
        except Exception as e:
            assert False, f"List response is not valid JSON: {e}, Response text: {list_response.text}"

        assert any(bug.get("id") == bug_id for bug in bugs_list), "Created bug report not found in list endpoint"

    finally:
        if bug_id:
            delete_response = requests.delete(
                f"{BASE_URL}/api/data/bugs/{bug_id}",
                headers=HEADERS,
                timeout=30
            )
            assert delete_response.status_code in (200, 204), f"Failed to delete bug report with id {bug_id}"

test_verify_bug_report_submission_and_metadata_storage()
